# Generated by Django 2.2 on 2020-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(default='https://www.studycode.com'),
            preserve_default=False,
        ),
    ]
